collections:
  "Godzilla (Showa) Collection": {tpdb_poster: 309070}
set:
  "Godzilla Raids Again (1955)": {tpdb_poster: 309108}
  "Godzilla, King of the Monsters! (1956)": {tpdb_poster: 309109}
  "Gigantis: The Fire Monster (1959)": {tpdb_poster: 309110}
  "King Kong vs. Godzilla (1962)": {tpdb_poster: 309111}
  "King Kong vs. Godzilla (1963)": {tpdb_poster: 309112}
  "Mothra vs. Godzilla (1964)": {tpdb_poster: 309113}
  "Godzilla vs. The Thing (1964)": {tpdb_poster: 309114}
  "Ghidorah, the Three-Headed Monster (1964)": {tpdb_poster: 309115}
  "Invasion of Astro-Monster (1965)": {tpdb_poster: 309116}
  "Ebirah, Horror of the Deep (1966)": {tpdb_poster: 309117}
  "Son of Godzilla (1967)": {tpdb_poster: 309118}
  "Destroy All Monsters (1968)": {tpdb_poster: 309119}
  "All Monsters Attack (1969)": {tpdb_poster: 309120}
  "Godzilla vs. Hedorah (1971)": {tpdb_poster: 309121}
  "Godzilla vs. Gigan (1972)": {tpdb_poster: 309122}
  "Godzilla vs. Megalon (1973)": {tpdb_poster: 309123}
  "Godzilla vs. Mechagodzilla (1974)": {tpdb_poster: 309124}
  "Terror of Mechagodzilla (1975)": {tpdb_poster: 309125}