collections:
  "Marvel Cinematic Universe": {tpdb_poster: 143466}
set:
  "WandaVision (2021)":
    tpdb_poster: 124699
    seasons:
      1: {tpdb_poster: 124700}
  "The Falcon and the Winter Soldier (2021)":
    tpdb_poster: 208010
    seasons:
      0: {tpdb_poster: 208011}
      1: {tpdb_poster: 208012}
  "Loki (2021)":
    tpdb_poster: 144829
    seasons:
      0: {tpdb_poster: 164197}
      1: {tpdb_poster: 144830}
  "What If...? (2021)":
    tpdb_poster: 167483
    seasons:
      1: {tpdb_poster: 167484}
  "Hawkeye (2021)":
    tpdb_poster: 192356
    seasons:
      0: {tpdb_poster: 192413}
      1: {tpdb_poster: 192357}
  "Moon Knight (2022)":
    tpdb_poster: 212414
    seasons:
      0: {tpdb_poster: 233946}
      1: {tpdb_poster: 213298}
  "Ms. Marvel (2022)":
    tpdb_poster: 241709
    seasons:
      1: {tpdb_poster: 241710}
  "She-Hulk: Attorney at Law (2022)":
    tpdb_poster: 257395
    seasons:
      1: {tpdb_poster: 257396}
  "I Am Groot (2022)":
    tpdb_poster: 259174
    seasons:
      1: {tpdb_poster: 259175}
  "Marvel's Agents of S.H.I.E.L.D. (2013)":
    tpdb_poster: 126114
    seasons:
      1: {tpdb_poster: 126115}
      2: {tpdb_poster: 126116}
      3: {tpdb_poster: 126117}
      4: {tpdb_poster: 126118}
      5: {tpdb_poster: 126119}
      6: {tpdb_poster: 126121}
      7: {tpdb_poster: 126124}
  "Marvel's Agent Carter (2015)":
    tpdb_poster: 126120
    seasons:
      1: {tpdb_poster: 126122}
      2: {tpdb_poster: 126123}
  "WHIH Newsfront (2015)":
    tpdb_poster: 149100
    seasons:
      1: {tpdb_poster: 149101}
      2: {tpdb_poster: 149102}
  "Marvel Studios: Legends (2021)":
    tpdb_poster: 194045
    seasons:
      1: {tpdb_poster: 194046}
  "The Daily Bugle (2019)":
    tpdb_poster: 214221
    seasons:
      1: {tpdb_poster: 214222}
      2: {tpdb_poster: 241977}
      3: {tpdb_poster: 241978}