collections:
  "Walt Disney Animation Studios": {tpdb_poster: 152809}
  "Pixar Animation Studios": {tpdb_poster: 148076}
  "Toy Story Collection": {tpdb_poster: 148077}
  "Monsters, Inc. Collection": {tpdb_poster: 148788}
  "Finding Nemo Collection": {tpdb_poster: 149220}
  "The Incredibles Collection": {tpdb_poster: 149226}
  "Cars Collection": {tpdb_poster: 149944}
  "Pixar Shorts": {tpdb_poster: 150984}
  "Bolt Collection": {tpdb_poster: 152815}
  "Frozen Complete Collection": {tpdb_poster: 152821}
  "Planes Collection": {tpdb_poster: 152837}
  "Tangled Collection": {tpdb_poster: 152842}
  "Wreck-It Ralph Collection": {tpdb_poster: 152847}
  "101 Dalmatians (Animated) Collection": {tpdb_poster: 156505}
  "Aladdin Complete Collection": {tpdb_poster: 156509}
  "Atlantis Collection": {tpdb_poster: 156518}
  "Bambi Collection": {tpdb_poster: 156520}
  "Beauty and the Beast Collection": {tpdb_poster: 156522}
  "Brother Bear Collection": {tpdb_poster: 156525}
  "Cinderella Collection": {tpdb_poster: 156527}
  "The Fox and the Hound Collection": {tpdb_poster: 156532}
  "A Goofy Movie Collection": {tpdb_poster: 156534}
  "Disney's Hercules Collection": {tpdb_poster: 156537}
  "The Jungle Book Collection": {tpdb_poster: 156542}
  "Lady and the Tramp Collection": {tpdb_poster: 156545}
  "The Hunchback of Notre Dame Collection": {tpdb_poster: 156540}
  "Lilo & Stitch Collection": {tpdb_poster: 156548}
  "The Lion King Collection": {tpdb_poster: 156563}
  "The Little Mermaid Collection": {tpdb_poster: 156566}
  "Mulan Collection": {tpdb_poster: 156573}
  "The Emperor's New Groove Collection": {tpdb_poster: 156575}
  "Peter Pan Collection": {tpdb_poster: 156577}
  "Pocahontas Collection": {tpdb_poster: 156579}
  "Tarzan (Animation) Collection": {tpdb_poster: 156581}
  "Tinker Bell Collection": {tpdb_poster: 156587}
  "Winnie the Pooh Collection": {tpdb_poster: 156596}
  "Caballeros Collection": {tpdb_poster: 235814}
  "Fantasia Collection": {tpdb_poster: 156531}
  "The Rescuers Collection": {tpdb_poster: 156585}
  "Sleeping Beauty Collection": {tpdb_poster: 156586}
  "Disney Live-Action Remakes": {tpdb_poster: 159360}
set:
  "Big Hero 6": {tpdb_poster: 152811}
  "Bolt": {tpdb_poster: 152816}
  "Chicken Little": {tpdb_poster: 152818}
  "Dinosaur": {tpdb_poster: 152819}
  "Frozen": {tpdb_poster: 152822}
  "Frozen II": {tpdb_poster: 152826}
  "Meet the Robinsons": {tpdb_poster: 152830}
  "Moana": {tpdb_poster: 152832}
  "Raya and the Last Dragon": {tpdb_poster: 152835}
  "Tangled": {tpdb_poster: 152843}
  "Wreck-It Ralph": {tpdb_poster: 152848}
  "Ralph Breaks the Internet": {tpdb_poster: 152849}
  "Zootopia": {tpdb_poster: 152850}
  "Snow White and the Seven Dwarfs": {tpdb_poster: 156173}
  "Pinocchio": {tpdb_poster: 156174}
  "Fantasia": {tpdb_poster: 156175}
  "Dumbo": {tpdb_poster: 156176}
  "Bambi": {tpdb_poster: 156177}
  "Saludos Amigos": {tpdb_poster: 156178}
  "The Three Caballeros": {tpdb_poster: 156179}
  "Make Mine Music": {tpdb_poster: 156180}
  "Fun and Fancy Free": {tpdb_poster: 156181}
  "Melody Time": {tpdb_poster: 156182}
  "The Adventures of Ichabod and Mr. Toad": {tpdb_poster: 156183}
  "Cinderella": {tpdb_poster: 156184}
  "Alice in Wonderland": {tpdb_poster: 156185}
  "Peter Pan": {tpdb_poster: 156186}
  "Lady and the Tramp": {tpdb_poster: 156187}
  "Sleeping Beauty": {tpdb_poster: 156188}
  "One Hundred and One Dalmatians": {tpdb_poster: 156189}
  "The Sword in the Stone": {tpdb_poster: 156190}
  "The Jungle Book": {tpdb_poster: 156191}
  "The Aristocats": {tpdb_poster: 156192}
  "Robin Hood": {tpdb_poster: 156193}
  "The Many Adventures of Winnie the Pooh": {tpdb_poster: 156194}
  "The Rescuers": {tpdb_poster: 156195}
  "The Fox and the Hound": {tpdb_poster: 156196}
  "The Black Cauldron": {tpdb_poster: 156197}
  "The Great Mouse Detective": {tpdb_poster: 156198}
  "Oliver & Company": {tpdb_poster: 156199}
  "The Little Mermaid": {tpdb_poster: 156200}
  "The Rescuers Down Under": {tpdb_poster: 156202}
  "Beauty and the Beast": {tpdb_poster: 156203}
  "Aladdin": {tpdb_poster: 156204}
  "The Lion King": {tpdb_poster: 156205}
  "Pocahontas": {tpdb_poster: 156206}
  "The Hunchback of Notre Dame": {tpdb_poster: 156207}
  "Hercules": {tpdb_poster: 156208}
  "Mulan": {tpdb_poster: 156209}
  "Tarzan": {tpdb_poster: 156210}
  "Fantasia 2000": {tpdb_poster: 156211}
  "The Emperor's New Groove": {tpdb_poster: 156212}
  "Atlantis: The Lost Empire": {tpdb_poster: 156213}
  "Lilo & Stitch": {tpdb_poster: 156214}
  "Treasure Planet": {tpdb_poster: 156215}
  "Brother Bear": {tpdb_poster: 156216}
  "Home on the Range": {tpdb_poster: 156217}
  "The Princess and the Frog": {tpdb_poster: 156218}
  "Winnie the Pooh": {tpdb_poster: 156219}
  "Encanto": {tpdb_poster: 201248}
  "Strange World": {tpdb_poster: 305812}
  "Toy Story": {tpdb_poster: 148078}
  "Toy Story 2": {tpdb_poster: 148079}
  "Toy Story 3": {tpdb_poster: 148080}
  "Toy Story 4": {tpdb_poster: 148081}
  "Soul": {tpdb_poster: 148423}
  "A Bug's Life": {tpdb_poster: 148426}
  "The Good Dinosaur": {tpdb_poster: 148427}
  "Onward": {tpdb_poster: 148428}
  "Monsters, Inc.": {tpdb_poster: 148789}
  "Mike's New Car": {tpdb_poster: 148790}
  "Monsters University": {tpdb_poster: 148791}
  "Party Central": {tpdb_poster: 148792}
  "Finding Nemo": {tpdb_poster: 149221}
  "Exploring the Reef": {tpdb_poster: 149222}
  "Finding Dory": {tpdb_poster: 149223}
  "Marine Life Interviews": {tpdb_poster: 149224}
  "Dory's Reef Cam": {tpdb_poster: 149225}
  "The Incredibles": {tpdb_poster: 149227}
  "Jack-Jack Attack": {tpdb_poster: 149228}
  "Mr. Incredible and Pals": {tpdb_poster: 149229}
  "Incredibles 2": {tpdb_poster: 149230}
  "Auntie Edna": {tpdb_poster: 149231}
  "Ratatouille": {tpdb_poster: 149233}
  "Cars": {tpdb_poster: 149945}
  "Cars 2": {tpdb_poster: 149946}
  "Cars 3": {tpdb_poster: 149947}
  "Up": {tpdb_poster: 149949}
  "WALL·E": {tpdb_poster: 149953}
  "Inside Out": {tpdb_poster: 149956}
  "Brave": {tpdb_poster: 149959}
  "Coco": {tpdb_poster: 149963}
  "Luca": {tpdb_poster: 150805}
  "Turning Red": {tpdb_poster: 160327}
  "Lightyear": {tpdb_poster: 242086}
  "The Adventures of André and Wally B.": {tpdb_poster: 150985}
  "Lamp Life": {tpdb_poster: 148087}
  "Ciao Alberto": {tpdb_poster: 190101}
  "Luxo Jr.": {tpdb_poster: 150986}
  "Riley's First Date": {tpdb_poster: 149957}
  "Your Friend the Rat": {tpdb_poster: 149234}
  "Burn-E": {tpdb_poster: 149954}
  "George and A.J.": {tpdb_poster: 149951}
  "Dug's Special Mission": {tpdb_poster: 149950}
  "22 vs. Earth": {tpdb_poster: 148424}
  "Toy Story Toons: Hawaiian Vacation": {tpdb_poster: 148083}
  "Toy Story Toons: Small Fry": {tpdb_poster: 148084}
  "Toy Story That Time Forgot": {tpdb_poster: 148086}
  "Red's Dream": {tpdb_poster: 150987}
  "Tin Toy": {tpdb_poster: 150988}
  "Knick Knack": {tpdb_poster: 150989}
  "Geri's Game": {tpdb_poster: 150990}
  "For the Birds": {tpdb_poster: 150991}
  "Boundin'": {tpdb_poster: 150992}
  "One Man Band": {tpdb_poster: 150993}
  "Lifted": {tpdb_poster: 150994}
  "Presto": {tpdb_poster: 150995}
  "Partly Cloudy": {tpdb_poster: 150996}
  "Day & Night": {tpdb_poster: 150997}
  "La luna": {tpdb_poster: 150998}
  "The Blue Umbrella": {tpdb_poster: 150999}
  "Lava": {tpdb_poster: 151000}
  "Sanjay's Super Team": {tpdb_poster: 151001}
  "Piper": {tpdb_poster: 151002}
  "Lou": {tpdb_poster: 151003}
  "Bao": {tpdb_poster: 151004}
  "Super Rhino": {tpdb_poster: 152817}
  "Frozen Fever": {tpdb_poster: 152823}
  "LEGO Frozen Northern Lights": {tpdb_poster: 152824}
  "Olaf's Frozen Adventure": {tpdb_poster: 152825}
  "Once Upon a Snowman": {tpdb_poster: 152827}
  "Planes": {tpdb_poster: 152838}
  "Planes: Fire & Rescue": {tpdb_poster: 152839}
  "Tangled Ever After": {tpdb_poster: 152844}
  "Tangled: Before Ever After": {tpdb_poster: 152845}
  "101 Dalmatians II: Patch's London Adventure": {tpdb_poster: 156506}
  "The Return of Jafar": {tpdb_poster: 156511}
  "Aladdin and the King of Thieves": {tpdb_poster: 156513}
  "Atlantis: Milo's Return": {tpdb_poster: 156519}
  "Bambi II": {tpdb_poster: 156521}
  "Beauty and the Beast: The Enchanted Christmas": {tpdb_poster: 156523}
  "Belle's Magical World": {tpdb_poster: 156524}
  "Brother Bear 2": {tpdb_poster: 156526}
  "Cinderella II: Dreams Come True": {tpdb_poster: 156528}
  "Cinderella III: A Twist in Time": {tpdb_poster: 156529}
  "The Fox and the Hound 2": {tpdb_poster: 156533}
  "A Goofy Movie": {tpdb_poster: 156535}
  "An Extremely Goofy Movie": {tpdb_poster: 156536}
  "Hercules: Zero to Hero": {tpdb_poster: 156538}
  "The Jungle Book 2": {tpdb_poster: 156543}
  "Lady and the Tramp II: Scamp's Adventure": {tpdb_poster: 156546}
  "The Hunchback of Notre Dame II": {tpdb_poster: 156541}
  "Stitch! The Movie": {tpdb_poster: 156549}
  "Lilo & Stitch 2: Stitch Has a Glitch": {tpdb_poster: 156550}
  "Leroy & Stitch": {tpdb_poster: 156551}
  "The Lion King II: Simba's Pride": {tpdb_poster: 156564}
  "The Lion King 1½": {tpdb_poster: 156565}
  "The Little Mermaid II: Return to the Sea": {tpdb_poster: 156567}
  "The Little Mermaid: Ariel's Beginning": {tpdb_poster: 156568}
  "Mulan II": {tpdb_poster: 156574}
  "Kronk's New Groove": {tpdb_poster: 156576}
  "Return to Never Land": {tpdb_poster: 156578}
  "Pocahontas II: Journey to a New World": {tpdb_poster: 156580}
  "Tarzan & Jane": {tpdb_poster: 156582}
  "Tarzan II": {tpdb_poster: 156583}
  "Tinker Bell": {tpdb_poster: 156588}
  "Tinker Bell and the Lost Treasure": {tpdb_poster: 156589}
  "Tinker Bell and the Great Fairy Rescue": {tpdb_poster: 156590}
  "Pixie Hollow Games": {tpdb_poster: 156591}
  "Secret of the Wings": {tpdb_poster: 156592}
  "Pixie Hollow Bake Off": {tpdb_poster: 156593}
  "Tinker Bell and the Pirate Fairy": {tpdb_poster: 156594}
  "Tinker Bell and the Legend of the NeverBeast": {tpdb_poster: 156595}
  "Pooh's Grand Adventure: The Search for Christopher Robin": {tpdb_poster: 156597}
  "The Tigger Movie": {tpdb_poster: 156598}
  "Piglet's Big Movie": {tpdb_poster: 156599}
  "Winnie the Pooh: Springtime with Roo": {tpdb_poster: 156600}
  "Pooh's Heffalump Movie": {tpdb_poster: 156601}
  "Legend of the Three Caballeros": {tpdb_poster: 235815}
  "Frankenweenie": {tpdb_poster: 152820}
  "Mars Needs Moms": {tpdb_poster: 152829}
  "The Nightmare Before Christmas": {tpdb_poster: 152834}
  "The Wild": {tpdb_poster: 152841}
  "Mickey's Christmas Carol": {tpdb_poster: 156220}
  "Mickey, Donald, Goofy: The Three Musketeers": {tpdb_poster: 156221}
  "Chip 'n Dale: Rescue Rangers": {tpdb_poster: 236603}
  "101 Dalmatians (1996)": {tpdb_poster: 159362}
  "102 Dalmatians (2000)": {tpdb_poster: 159363}
  "Alice in Wonderland (2010)": {tpdb_poster: 159364}
  "Maleficent (2014)": {tpdb_poster: 159365}
  "Cinderella (2015)": {tpdb_poster: 159366}
  "The Jungle Book (2016)": {tpdb_poster: 159367}
  "Alice Through the Looking Glass (2016)": {tpdb_poster: 159368}
  "Beauty and the Beast (2017)": {tpdb_poster: 159369}
  "Christopher Robin (2018)": {tpdb_poster: 159370}
  "Dumbo (2019)": {tpdb_poster: 159371}
  "Aladdin (2019)": {tpdb_poster: 159372}
  "The Lion King (2019)": {tpdb_poster: 159373}
  "Maleficent: Mistress of Evil (2019)": {tpdb_poster: 159374}
  "Lady and the Tramp (2019)": {tpdb_poster: 159375}
  "Mulan (2020)": {tpdb_poster: 159376}
  "Cruella (2021)": {tpdb_poster: 159377}
  "Pinocchio (2022)": {tpdb_poster: 265424}
