name: Image-Set-Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  Image-Set-Update-Daily:
    if: github.repository_owner == 'meisnate12'
    runs-on: ubuntu-latest
    steps:

      - name: Get current date
        id: date
        run: echo "date=$(date +'%B %d, %Y %I:%M %p')" >> $GITHUB_OUTPUT

      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.x"

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Image Set Update
        env:
          TMDBAPI: ${{ secrets.TMDBAPI }}
          TRAKT_ID: ${{ secrets.TRAKT_ID }}
          TRAKT_TOKEN: ${{ secrets.TRAKT_TOKEN }}
        run: python set_update.py

      - name: Check Diff
        id: verify_diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit & Push Changes
        if: steps.verify_diff.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update at ${{ steps.date.outputs.date }} UTC" -a
          git push origin master